### ISSUE TITLE
Formatting could use a nice touch of BURNITWITHFIRE-tool

### ISSUE THREAD

**Issue by Levitanious** [Levitanious/SuperTBCMacro#5]
Things like these:

![image](https://user-images.githubusercontent.com/7385970/35855605-549c5f4a-0b66-11e8-9538-3bd31d245500.png)
...are _somewhat_ scary to read.

P.S. I'm exaggerating, of course.

**Comment by Levitanious** [comment]
P.P.S. Or am i?...

**Comment by Levitanious** [comment]
#### Some points to add:
- Tabs! Tabs are all around!
- Code isn't documented much, that sucks
- What about UTF-8?

**Comment by berserkingyadis** [comment]
To quote the GCC Coding Conventions, 80 would be a nice width for the code.

_Lines shall be at most 80 columns._

[src](https://gcc.gnu.org/codingconventions.html#Line)

**Comment by Levitanious** [comment]
Coming from Python, i know the 80 all too well :>

Totally agree.
